## Numpy

- Designed for fast numerical computing

In [2]:
import numpy as np
import time

In [3]:
arr = np.array([2,4,6,8,10,12])
print(arr, type(arr))

[ 2  4  6  8 10 12] <class 'numpy.ndarray'>


#### Python Lists vs NumPy Arrays
1. NumPy arrays are faster (optimized in C)
2. NumPy stores data in continuous memory blocks
3. Uses less memory (optimized storage)
4. Built-in mathemetical functions
5. Supports direct vectorized operations

In [8]:
# execution performance between python list and numpy arrays
size = 10_000_000

#python List
py_list = list(range(size))
start_time = time.time()
sq_list = [x**2 for x in py_list]
end_time = time.time()

# Numpy Array
np_arr = np.array(py_list)
start = time.time()
sq_arr = np_arr ** 2
end = time.time()

# print(f"Time taken by python list is: {end_time - start_time} seconds")
# print(f"Time taken by Numpy Array is: {end - start} seconds")

Time taken by python list is: 9.229332208633423 seconds
Time taken by Numpy Array is: 0.08644270896911621 seconds


In [17]:
# creating arrays from lists
arr = np.array([1,2,3,14,5,6])
print(arr, type(arr), arr.shape, arr.dtype)

arr2 = np.array([9,8,7,6, "Wali"])
print(arr2, type(arr2), arr2.shape, arr2.dtype)

arr3 = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
print(arr3, arr3.shape)

[ 1  2  3 14  5  6] <class 'numpy.ndarray'> (6,) int64
['9' '8' '7' '6' 'Wali'] <class 'numpy.ndarray'> (5,) <U21
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]] (4, 3)


In [34]:
# Creating arrays
arr = np.zeros((2,3))       # by default it will made in float
print(arr, arr.shape)

arr2 = np.ones((5,), dtype = "int64")
print(arr2, arr2.shape)

arr3 = np.full((3,5), 69)
print(arr3, arr3.shape)

arr4 = np.eye(3)           # give 1 in diagonals in square matrix
print(arr4)

arr5 = np.arange(0,21,2)         # range elements
print(arr5)

arr6 = np.linspace(1,100,3)         # evenly spaced elements
print(arr6)

[[0. 0. 0.]
 [0. 0. 0.]] (2, 3)
[1 1 1 1 1] (5,)
[[69 69 69 69 69]
 [69 69 69 69 69]
 [69 69 69 69 69]] (3, 5)
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[ 0  2  4  6  8 10 12 14 16 18 20]
[  1.   50.5 100. ]


In [46]:
# copy vs view
list = [1,2,3,4,5,6,7,8,9]
sub_list = list[1:4]
print(sub_list)
sub_list[1] = 69
print(sub_list)
print(list)

arr = np.array([1,2,3,4,5,6,7,8,9])
sub_arr = arr[1:4]
print(sub_arr)
sub_arr[1] = 69
print(sub_arr)
print(arr)

# In Python lists, slicing creates a new list, so changes don’t affect the original.
# In NumPy arrays, slicing returns a view that shares memory with the original array,
# so modifying the slice also modifies the original array.

[2, 3, 4]
[2, 69, 4]
[1, 2, 3, 4, 5, 6, 7, 8, 9]
[2 3 4]
[ 2 69  4]
[ 1  2 69  4  5  6  7  8  9]
